### ISSUE TITLE
Merge develop branch to master

### ISSUE THREAD

**Issue by guyomes** [lambdalisue/Shareboard#4]
The master branch contains several bugs that are fixed in the develop branch. In particular, the master branch does not work with the vim plugin shareboard.vim. That could easily be fixed by merging the develop branch back in the master branch. As a bonus, that would automatically fix the AUR package as well. 

And thank you for this nice tool !

**Comment by lambdalisue** [comment]
Thanks for the comment! I totally forgot to merge the hotfix on the master branch. You saved me :+1: 

Now the version of Shareboard on [pypi](https://pypi.python.org/pypi/shareboard) is 0.1.7 which include the hotfix thus use `pip install Shareboard` to install it.

Thanks again to remind me.
